package com.example.app.pipeline.stage.agent;

import com.example.app.dto.Artifact;
import com.example.app.pipeline.ContextPipelineStage;
import com.example.app.pipeline.context.ConversationContext;
import com.example.app.service.tool.ToolExecutor;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Agent 工具调用执行阶段
 *
 * 遍历 ctx.toolCalls，通过 {@link ToolExecutor} 逐一执行，
 * 将结果（{@link ConversationContext.ToolResultRecord}）追加到 ctx.toolResults。
 *
 * 单个工具执行失败不会中断整体流程：失败结果以 success=false 标记，
 * 后续 LLM 轮次可据此决定是否重试或换一种方式回答。
 *
 * order=650（AGENT 阶段，在 toolCallDetectionStage(610) 之后）
 */
@Component
@RequiredArgsConstructor
@Slf4j
public class ToolInvocationStage implements ContextPipelineStage {

    private final ToolExecutor toolExecutor;

    /**
     * 匹配 Markdown 图片语法：![alt](url)
     * URL 支持 http(s):// 或 data:image/...;base64,... 两种形式。
     * 用于自动从 Tool 返回结果中提取图片，加入 ctx.artifacts，
     * 避免依赖 LLM 是否原样输出 Markdown。
     */
    private static final Pattern IMAGE_MARKDOWN_PATTERN = Pattern.compile(
            "!\\[[^\\]]*\\]\\((https?://[^\\s)]+|data:image/[^\\s)]+)\\)");

    @Override
    public Phase getPhase() {
        return Phase.AGENT;
    }

    @Override
    public String getName() {
        return "toolInvocationStage";
    }

    @Override
    public void execute(ConversationContext ctx) {
        if (ctx.getToolCalls().isEmpty()) {
            return;
        }

        // 保留上一轮的 toolResults 历史，仅追加本轮结果
        for (ConversationContext.ToolCallRecord call : ctx.getToolCalls()) {
            ConversationContext.ToolResultRecord result = toolExecutor.execute(call, ctx.getUserId());
            ctx.getToolResults().add(result);
            if (!result.success()) {
                log.warn("[ToolInvocation] Tool '{}' failed: {}", call.toolName(), result.errorMessage());
            } else {
                // 扫描 Tool 返回结果中的图片 Markdown，自动提取 URL 加入 ctx.artifacts。
                // 这样前端通过 SSE done.artifacts → message.images 渲染图片，
                // 不依赖 LLM 是否在最终回复中原样输出 Markdown。
                collectImageArtifacts(ctx, call.toolName(), String.valueOf(result.result()));
            }

            // 推送 Agent 思考过程：单个工具执行结果（含实际调用的模型）
            Map<String, Object> data = new LinkedHashMap<>();
            data.put("toolName", call.toolName());
            data.put("toolCallId", call.toolCallId());
            data.put("success", result.success());
            data.put("result", result.result());
            data.put("model", result.model());
            if (!result.success()) {
                data.put("errorMessage", result.errorMessage());
            }
            ctx.emitAgentThinking("tool_execution", data);
        }
        log.info("[ToolInvocation] Executed {} tool call(s), {} success, {} failed",
                ctx.getToolCalls().size(),
                ctx.getToolResults().stream().filter(ConversationContext.ToolResultRecord::success).count(),
                ctx.getToolResults().stream().filter(r -> !r.success()).count());
    }

    /**
     * 扫描 Tool 返回结果中的图片 Markdown（{@code ![alt](url)}），把 URL 提取为
     * {@link Artifact#image(String, String)} 加入 ctx.artifacts。
     *
     * 设计原因：ImageGenerationTool 等图片类 Tool 返回 Markdown 字符串供 LLM 看到
     * "图片已生成"，但 LLM 通常不会原样输出该 Markdown，导致前端拿不到图片 URL。
     * 在此处统一提取，保证 SSE done.artifacts 中包含图片，前端 message.images 可渲染。
     */
    private void collectImageArtifacts(ConversationContext ctx, String toolName, String resultText) {
        if (resultText == null || resultText.isBlank()) {
            return;
        }
        Matcher matcher = IMAGE_MARKDOWN_PATTERN.matcher(resultText);
        boolean found = false;
        while (matcher.find()) {
            String url = matcher.group(1);
            if (ctx.getArtifacts() == null) {
                ctx.setArtifacts(new ArrayList<>());
            }
            ctx.getArtifacts().add(Artifact.image(url, "Generated by " + toolName));
            found = true;
            log.info("[ToolInvocation] Tool '{}' produced image artifact: {}", toolName,
                    url.length() > 80 ? url.substring(0, 80) + "..." : url);
        }
        if (!found) {
            return;
        }
        // 简单去重：同一 URL 不重复加入。O(n^2) 在 artifact 数量小时可接受。
        List<Artifact> artifacts = ctx.getArtifacts();
        if (artifacts.size() > 1) {
            List<Artifact> deduped = new ArrayList<>();
            for (Artifact a : artifacts) {
                boolean dup = false;
                for (Artifact existing : deduped) {
                    if (a.url() != null && a.url().equals(existing.url()) && "image".equals(a.type())) {
                        dup = true;
                        break;
                    }
                }
                if (!dup) {
                    deduped.add(a);
                }
            }
            ctx.setArtifacts(deduped);
        }
    }

    @Override
    public boolean isApplicable(ConversationContext ctx) {
        return ctx.isAgentMode();
    }

    @Override
    public int getOrder() {
        return 650;
    }

    @Override
    public boolean isCritical() {
        return false;
    }
}
